"""
Azure DevOps pipeline template generator.

Generates azure-pipelines.yml files supporting multi-stage pipelines
with approvals, environments, and Azure-specific integrations.
"""

from src.questionnaire import (
    DeployTarget,
    Language,
    NotificationChannel,
    ProjectConfig,
    TestFramework,
)


class AzureDevOpsTemplate:
    """Template engine for Azure DevOps pipelines."""

    def __init__(self, config: ProjectConfig) -> None:
        """Initialize with project configuration."""
        self.config = config

    def render(self) -> str:
        """Render the complete azure-pipelines.yml content."""
        sections = [
            self._render_header(),
            self._render_trigger(),
            self._render_variables(),
            self._render_stages(),
        ]
        return "\n".join(sections)

    def _render_header(self) -> str:
        """Render header comments."""
        return (
            f"# Auto-generated CI/CD Pipeline for {self.config.project_name}\n"
            "# Platform: Azure DevOps\n"
            "# Generated by cicd-gen\n"
        )

    def _render_trigger(self) -> str:
        """Render trigger configuration."""
        branches = "\n".join([f"    - {b}" for b in self.config.branches_to_track])
        return (
            "trigger:\n"
            "  branches:\n"
            "    include:\n"
            f"{branches}\n"
            "\n"
            "pr:\n"
            "  branches:\n"
            "    include:\n"
            f"{branches}\n"
        )

    def _render_variables(self) -> str:
        """Render global variables."""
        lines = ["variables:"]
        if self.config.docker_enabled:
            lines.append("  dockerImage: '$(containerRegistry)/$(imageRepository):$(build.BuildId)'")
        if self.config.code_coverage:
            lines.append(f"  coverageThreshold: '{self.config.coverage_threshold}'")
        return "\n".join(lines) + "\n\n"

    def _render_stages(self) -> str:
        """Render all pipeline stages."""
        stages = [self._render_build_stage()]
        if self.config.test_framework.value != "none":
            stages.append(self._render_test_stage())
        if self.config.linting:
            stages.append(self._render_lint_stage())
        if self.config.security_scan:
            stages.append(self._render_security_stage())
        if self.config.code_coverage:
            stages.append(self._render_coverage_stage())
        if self.config.docker_enabled:
            stages.append(self._render_docker_stage())
        if self.config.deploy_target != DeployTarget.NONE:
            stages.append(self._render_deploy_stage())
        if self.config.notification != NotificationChannel.NONE:
            stages.append(self._render_notify_stage())

        return "\n".join(stages)

    def _render_build_stage(self) -> str:
        """Render build stage."""
        pool = self._pool_agent()
        steps = self._build_steps()
        steps_yaml = "\n".join([f"        - {s}" for s in steps])

        return (
            "stages:\n"
            "- stage: Build\n"
            "  displayName: 'Build Stage'\n"
            "  jobs:\n"
            "  - job: BuildJob\n"
            "    displayName: 'Build'\n"
            f"    pool:\n      vmImage: '{pool}'\n"
            "    steps:\n"
            f"{steps_yaml}\n"
            "    - task: PublishBuildArtifacts@1\n"
            "      inputs:\n"
            "        pathToPublish: '$(Build.ArtifactStagingDirectory)'\n"
            "        artifactName: 'drop'\n"
        )

    def _render_test_stage(self) -> str:
        """Render test stage."""
        pool = self._pool_agent()
        steps = self._test_steps()
        steps_yaml = "\n".join([f"        - {s}" for s in steps])

        return (
            "\n- stage: Test\n"
            "  displayName: 'Test Stage'\n"
            "  dependsOn: Build\n"
            "  jobs:\n"
            "  - job: TestJob\n"
            "    displayName: 'Run Tests'\n"
            f"    pool:\n      vmImage: '{pool}'\n"
            "    steps:\n"
            f"{steps_yaml}\n"
            "    - task: PublishTestResults@2\n"
            "      inputs:\n"
            "        testResultsFormat: 'JUnit'\n"
            "        testResultsFiles: '**/test-results.xml'\n"
            "        mergeTestResults: true\n"
            "        testRunTitle: '$(Build.DefinitionName)'\n"
            "      condition: succeededOrFailed()\n"
        )

    def _render_lint_stage(self) -> str:
        """Render lint stage."""
        pool = self._pool_agent()
        steps = self._lint_steps()
        steps_yaml = "\n".join([f"        - {s}" for s in steps])

        return (
            "\n- stage: Lint\n"
            "  displayName: 'Lint Stage'\n"
            "  jobs:\n"
            "  - job: LintJob\n"
            "    displayName: 'Lint'\n"
            f"    pool:\n      vmImage: '{pool}'\n"
            "    steps:\n"
            f"{steps_yaml}\n"
        )

    def _render_security_stage(self) -> str:
        """Render security scan stage."""
        pool = self._pool_agent()
        return (
            "\n- stage: Security\n"
            "  displayName: 'Security Scan'\n"
            "  dependsOn: Build\n"
            "  jobs:\n"
            "  - job: SecurityScan\n"
            "    displayName: 'Security Scanning'\n"
            f"    pool:\n      vmImage: '{pool}'\n"
            "    steps:\n"
            "        - task: DownloadBuildArtifacts@1\n"
            "          inputs:\n"
            "            buildType: 'current'\n"
            "            downloadType: 'single'\n"
            "            artifactName: 'drop'\n"
            "            downloadPath: '$(System.ArtifactsDirectory)'\n"
            "        - task: Trivy@1\n"
            "          inputs:\n"
            "            version: 'latest'\n"
            "            docker: false\n"
            "            debug: false\n"
            "            path: '$(System.DefaultWorkingDirectory)'\n"
            "            exitCode: 0\n"
            "        - script: |\n"
            f"            {self._sast_script()}\n"
            "          displayName: 'SAST Scan'\n"
        )

    def _render_coverage_stage(self) -> str:
        """Render coverage stage."""
        pool = self._pool_agent()
        steps = self._coverage_steps()
        steps_yaml = "\n".join([f"        - {s}" for s in steps])

        return (
            "\n- stage: Coverage\n"
            "  displayName: 'Code Coverage'\n"
            "  dependsOn: Test\n"
            "  jobs:\n"
            "  - job: CoverageJob\n"
            "    displayName: 'Coverage Analysis'\n"
            f"    pool:\n      vmImage: '{pool}'\n"
            "    steps:\n"
            f"{steps_yaml}\n"
            "    - task: PublishCodeCoverageResults@1\n"
            "      inputs:\n"
            "        codeCoverageTool: 'Cobertura'\n"
            "        summaryFileLocation: '**/coverage.xml'\n"
            "        pathToSources: '$(System.DefaultWorkingDirectory)'\n"
        )

    def _render_docker_stage(self) -> str:
        """Render Docker build stage."""
        pool = self._pool_agent()
        return (
            "\n- stage: Docker\n"
            "  displayName: 'Docker Build'\n"
            "  dependsOn: [Build, Test]\n"
            "  jobs:\n"
            "  - job: DockerBuild\n"
            "    displayName: 'Build & Push Image'\n"
            f"    pool:\n      vmImage: '{pool}'\n"
            "    steps:\n"
            "        - task: DownloadBuildArtifacts@1\n"
            "          inputs:\n"
            "            buildType: 'current'\n"
            "            downloadType: 'single'\n"
            "            artifactName: 'drop'\n"
            "            downloadPath: '$(System.ArtifactsDirectory)'\n"
            "        - task: Docker@2\n"
            "          displayName: 'Build Image'\n"
            "          inputs:\n"
            "            containerRegistry: '$(dockerRegistryServiceConnection)'\n"
            "            repository: '$(imageRepository)'\n"
            "            command: 'buildAndPush'\n"
            "            Dockerfile: '**/Dockerfile'\n"
            "            tags: |\n"
            "              $(Build.BuildId)\n"
            "              latest\n"
        )

    def _render_deploy_stage(self) -> str:
        """Render deployment stage with approval."""
        deploy_steps = self._deploy_steps()
        return (
            "\n- stage: Deploy\n"
            f"  displayName: 'Deploy to {self.config.deploy_target.value.upper()}'\n"
            "  dependsOn: [Build, Test]\n"
            "  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))\n"
            "  jobs:\n"
            "  - deployment: DeployJob\n"
            "    displayName: 'Deploy'\n"
            "    pool:\n      vmImage: 'ubuntu-latest'\n"
            "    environment: 'production'\n"
            "    strategy:\n"
            "      runOnce:\n"
            "        deploy:\n"
            "          steps:\n"
            f"            - script: |\n"
            f"                {deploy_steps}\n"
            "              displayName: 'Deploy application'\n"
            "            # <!-- DEPLOY_STRATEGY_PLACEHOLDER -->\n"
        )

    def _render_notify_stage(self) -> str:
        """Render notification stage."""
        pool = self._pool_agent()
        return (
            "\n- stage: Notify\n"
            "  displayName: 'Notifications'\n"
            "  dependsOn: [Build, Test, Deploy]\n"
            "  condition: always()\n"
            "  jobs:\n"
            "  - job: NotifyJob\n"
            "    displayName: 'Send Notifications'\n"
            f"    pool:\n      vmImage: '{pool}'\n"
            "    steps:\n"
            "        - script: |\n"
            "            echo 'Sending notifications...'\n"
            "          displayName: 'Notify'\n"
        )

    def _pool_agent(self) -> str:
        """Select pool agent image."""
        return "ubuntu-latest"

    def _build_steps(self) -> list[str]:
        """Build steps for Azure DevOps."""
        checkout = "task: Checkout@1"
        steps = [checkout]

        setup_steps = {
            Language.PYTHON: [
                "task: UsePythonVersion@0\n          inputs:\n            versionSpec: '3.11'",
                "script: |\n          pip install -r requirements.txt\n        displayName: 'Install dependencies'",
            ],
            Language.NODEJS: [
                "task: NodeTool@0\n          inputs:\n            versionSpec: '20.x'",
                "script: |\n          npm ci\n        displayName: 'Install dependencies'",
                "script: |\n          npm run build\n        displayName: 'Build project'",
            ],
            Language.GO: [
                "task: GoTool@0\n          inputs:\n            version: '1.21'",
                "script: |\n          go mod download\n          go build -v ./...\n        displayName: 'Build project'",
            ],
        }
        steps.extend(setup_steps.get(self.config.language, []))
        return steps

    def _test_steps(self) -> list[str]:
        """Test steps for Azure DevOps."""
        steps = []
        if self.config.language == Language.PYTHON:
            steps.append(
                "task: UsePythonVersion@0\n          inputs:\n            versionSpec: '3.11'"
            f"\n          script: |\n          pip install -r requirements.txt\n          pytest -v --junitxml=test-results.xml\n        displayName: 'Run tests'"
            )
        elif self.config.language == Language.NODEJS:
            steps.append(
                "script: |\n          npm ci\n          npm test\n        displayName: 'Run tests'"
            )
        elif self.config.language == Language.GO:
            steps.append(
                "script: |\n          go test -v ./...\n        displayName: 'Run tests'"
            )
        return steps

    def _lint_steps(self) -> list[str]:
        """Lint steps for Azure DevOps."""
        commands = {
            Language.PYTHON: "pip install flake8 && flake8 .",
            Language.NODEJS: "npm run lint",
            Language.GO: "go vet ./... && gofmt -d .",
            Language.RUST: "cargo clippy -- -D warnings",
            Language.JAVA: "mvn checkstyle:check",
        }
        cmd = commands.get(self.config.language, "echo 'No linting'")
        return [f"script: |\n          {cmd}\n        displayName: 'Run linter'"]

    def _sast_script(self) -> str:
        """SAST script for Azure DevOps."""
        if self.config.language == Language.PYTHON:
            return "pip install bandit && bandit -r . || true"
        elif self.config.language == Language.NODEJS:
            return "npm audit || true"
        return "echo 'SAST not configured'"

    def _coverage_steps(self) -> list[str]:
        """Coverage steps for Azure DevOps."""
        steps = []
        if self.config.language == Language.PYTHON:
            steps.append(
                "task: UsePythonVersion@0\n          inputs:\n            versionSpec: '3.11'"
                f"\n          script: |\n          pip install pytest-cov\n          pytest --cov=. --cov-report=xml --cov-report=html --cov-fail-under={self.config.coverage_threshold}\n        displayName: 'Run tests with coverage'"
            )
        elif self.config.language == Language.NODEJS:
            steps.append(
                "script: |\n          npm run test:coverage\n        displayName: 'Run tests with coverage'"
            )
        elif self.config.language == Language.GO:
            steps.append(
                "script: |\n          go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out -o coverage.html\n        displayName: 'Run tests with coverage'"
            )
        return steps

    def _deploy_steps(self) -> str:
        """Deploy steps for Azure DevOps."""
        commands = {
            DeployTarget.KUBERNETES: (
                "echo $(KUBECONFIG) | base64 -d > kubeconfig\n"
                "export KUBECONFIG=kubeconfig\n"
                "kubectl set image deployment/app app=$(dockerImage)"
            ),
            DeployTarget.AZURE: (
                "az webapp deployment container config --enable-cd true "
                "--name $(appName) --resource-group $(resourceGroup)"
            ),
            DeployTarget.AWS: (
                "aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)\n"
                "aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)\n"
                "aws elasticbeanstalk update-environment --environment-name prod"
            ),
            DeployTarget.DOCKER_HUB: (
                "docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)\n"
                "docker push $(dockerImage)"
            ),
        }
        return commands.get(self.config.deploy_target, "echo 'No deploy steps'")
