"""
CircleCI pipeline template generator.

Generates .circleci/config.yml with workflows, orbs, and
Docker executor configurations.
"""

from src.questionnaire import (
    DeployTarget,
    Language,
    NotificationChannel,
    ProjectConfig,
    TestFramework,
)


class CircleCITemplate:
    """Template engine for CircleCI configurations."""

    def __init__(self, config: ProjectConfig) -> None:
        """Initialize with project configuration."""
        self.config = config

    def render(self) -> str:
        """Render the complete .circleci/config.yml content."""
        sections = [
            self._render_header(),
            self._render_version(),
            self._render_orbs(),
            self._render_parameters(),
            self._render_executors(),
            self._render_commands(),
            self._render_jobs(),
            self._render_workflows(),
        ]
        return "\n".join(sections)

    def _render_header(self) -> str:
        """Render header comments."""
        return (
            f"# Auto-generated CI/CD Pipeline for {self.config.project_name}\n"
            "# Platform: CircleCI\n"
            "# Generated by cicd-gen\n"
        )

    def _render_version(self) -> str:
        """Render CircleCI version."""
        return "version: 2.1\n\n"

    def _render_orbs(self) -> str:
        """Render orb imports."""
        orbs = ["  slack: circleci/slack@4.12.5"]
        if self.config.docker_enabled:
            orbs.append("  docker: circleci/docker@2.6.0")
        if self.config.deploy_target == DeployTarget.KUBERNETES:
            orbs.append("  kubernetes: circleci/kubernetes@1.3.1")
        if self.config.code_coverage:
            orbs.append("  codecov: codecov/codecov@3.3.0")
        return "orbs:\n" + "\n".join(orbs) + "\n\n"

    def _render_parameters(self) -> str:
        """Render pipeline parameters."""
        lines = [
            "parameters:",
            "  working_dir:",
            "    type: string",
            f"    default: \"{self.config.working_directory}\"",
        ]
        if self.config.docker_enabled:
            lines.extend([
                "  docker_image:",
                "    type: string",
                '    default: "$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"',
            ])
        return "\n".join(lines) + "\n\n"

    def _render_executors(self) -> str:
        """Render executor definitions."""
        image = self._docker_image()
        return (
            "executors:\n"
            "  default:\n"
            "    docker:\n"
            f"      - image: {image}\n"
            "    working_directory: ~/project\n"
            "    environment:\n"
            "      TERM: xterm-color\n"
            "\n"
        )

    def _render_commands(self) -> str:
        """Render reusable commands."""
        commands = []

        # Checkout and setup command
        commands.append(
            "  setup:\n"
            "    description: 'Checkout and install dependencies'\n"
            "    steps:\n"
            "      - checkout\n"
            f"{self._setup_steps()}"
        )

        return "commands:\n" + "\n".join(commands) + "\n\n"

    def _render_jobs(self) -> str:
        """Render all job definitions."""
        jobs = [self._render_build_job()]
        if self.config.test_framework.value != "none":
            jobs.append(self._render_test_job())
        if self.config.linting:
            jobs.append(self._render_lint_job())
        if self.config.security_scan:
            jobs.append(self._render_security_job())
        if self.config.code_coverage:
            jobs.append(self._render_coverage_job())
        if self.config.docker_enabled:
            jobs.append(self._render_docker_job())
        if self.config.deploy_target != DeployTarget.NONE:
            jobs.append(self._render_deploy_job())
        if self.config.notification != NotificationChannel.NONE:
            jobs.append(self._render_notify_job())

        return "jobs:\n" + "\n".join(jobs) + "\n"

    def _render_build_job(self) -> str:
        """Render build job."""
        build_cmd = self._build_command()
        return (
            "  build:\n"
            "    executor: default\n"
            "    steps:\n"
            "      - setup\n"
            f"      - run:\n"
            f"          name: Build\n"
            f"          command: {build_cmd}\n"
            "      - persist_to_workspace:\n"
            "          root: .\n"
            "          paths:\n"
            "            - .\n"
        )

    def _render_test_job(self) -> str:
        """Render test job."""
        test_cmd = self._test_command()
        return (
            "\n  test:\n"
            "    executor: default\n"
            "    steps:\n"
            "      - setup\n"
            f"      - run:\n"
            f"          name: Run tests\n"
            f"          command: {test_cmd}\n"
            "      - store_test_results:\n"
            "          path: test-results\n"
            "      - store_artifacts:\n"
            "          path: test-results\n"
        )

    def _render_lint_job(self) -> str:
        """Render lint job."""
        lint_cmd = self._lint_command()
        return (
            "\n  lint:\n"
            "    executor: default\n"
            "    steps:\n"
            "      - setup\n"
            f"      - run:\n"
            f"          name: Lint\n"
            f"          command: {lint_cmd}\n"
        )

    def _render_security_job(self) -> str:
        """Render security scan job."""
        return (
            "\n  security:\n"
            "    executor: default\n"
            "    steps:\n"
            "      - checkout\n"
            "      - run:\n"
            "          name: Security scan\n"
            "          command: |\n"
            "            echo 'Running security scan'\n"
            f"{self._security_steps()}"
        )

    def _render_coverage_job(self) -> str:
        """Render coverage job."""
        return (
            "\n  coverage:\n"
            "    executor: default\n"
            "    steps:\n"
            "      - setup\n"
            "      - run:\n"
            "          name: Run tests with coverage\n"
            "          command: |\n"
            f"{self._coverage_command()}\n"
            "      - codecov/upload:\n"
            "          file: coverage.xml\n"
            "      - store_artifacts:\n"
            "          path: coverage_html\n"
        )

    def _render_docker_job(self) -> str:
        """Render Docker build/push job."""
        return (
            "\n  docker_build:\n"
            "    executor: default\n"
            "    steps:\n"
            "      - setup_remote_docker:\n"
            "          docker_layer_caching: true\n"
            "      - checkout\n"
            "      - run:\n"
            "          name: Build Docker image\n"
            "          command: |\n"
            "            docker build -t << pipeline.parameters.docker_image >>:$CIRCLE_SHA1 .\n"
            "      - run:\n"
            "          name: Push to registry\n"
            "          command: |\n"
            "            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin\n"
            "            docker push << pipeline.parameters.docker_image >>:$CIRCLE_SHA1\n"
        )

    def _render_deploy_job(self) -> str:
        """Render deployment job."""
        deploy_cmd = self._deploy_command()
        return (
            "\n  deploy:\n"
            "    executor: default\n"
            "    steps:\n"
            "      - checkout\n"
            "      - run:\n"
            "          name: Deploy\n"
            "          command: |\n"
            f"{deploy_cmd}\n"
            "          # <!-- DEPLOY_STRATEGY_PLACEHOLDER -->\n"
        )

    def _render_notify_job(self) -> str:
        """Render notification job."""
        return (
            "\n  notify:\n"
            "    executor: default\n"
            "    steps:\n"
            "      - slack/notify:\n"
            "          event: fail\n"
            "          template: basic_fail_1\n"
            "      - slack/notify:\n"
            "          event: pass\n"
            "          template: success_tagged_deploy_1\n"
        )

    def _render_workflows(self) -> str:
        """Render workflow definitions."""
        branches = ", ".join([f"\"{b}\"" for b in self.config.branches_to_track])
        jobs = [
            "      - build",
        ]
        if self.config.test_framework.value != "none":
            jobs.append("      - test:\n          requires: [build]")
        if self.config.linting:
            jobs.append("      - lint")
        if self.config.security_scan:
            jobs.append("      - security")
        if self.config.code_coverage:
            jobs.append("      - coverage:\n          requires: [test]")
        if self.config.docker_enabled:
            jobs.append("      - docker_build:\n          requires: [build, test]")
        if self.config.deploy_target != DeployTarget.NONE:
            deps = "[build, test]"
            if self.config.docker_enabled:
                deps = "[build, test, docker_build]"
            jobs.append(f"      - deploy:\n          requires: {deps}\n          filters:\n            branches:\n              only: main")
        if self.config.notification != NotificationChannel.NONE:
            jobs.append("      - notify:\n          requires: [deploy]\n          filters:\n            branches:\n              only: main")

        jobs_yaml = "\n".join(jobs)
        return (
            "workflows:\n"
            "  ci_cd_pipeline:\n"
            f"    jobs:\n{jobs_yaml}\n"
        )

    def _docker_image(self) -> str:
        """Select Docker image for executor."""
        images = {
            Language.PYTHON: "cimg/python:3.11",
            Language.NODEJS: "cimg/node:20.0",
            Language.GO: "cimg/go:1.21",
            Language.RUST: "cimg/rust:1.75",
            Language.JAVA: "cimg/openjdk:21.0",
            Language.DOCKER: "cimg/base:stable",
        }
        return images.get(self.config.language, "cimg/base:stable")

    def _setup_steps(self) -> str:
        """Generate setup steps based on language."""
        if self.config.language == Language.PYTHON:
            return (
                "      - restore_cache:\n"
                "          keys:\n"
                "            - v1-dependencies-{{ checksum \"requirements.txt\" }}\n"
                "            - v1-dependencies-\n"
                "      - run:\n"
                "          name: Install dependencies\n"
                "          command: pip install -r requirements.txt\n"
                "      - save_cache:\n"
                "          paths:\n"
                "            - ./.cache/pip\n"
                "          key: v1-dependencies-{{ checksum \"requirements.txt\" }}\n"
            )
        elif self.config.language == Language.NODEJS:
            return (
                "      - restore_cache:\n"
                "          keys:\n"
                "            - v1-dependencies-{{ checksum \"package-lock.json\" }}\n"
                "            - v1-dependencies-\n"
                "      - run:\n"
                "          name: Install dependencies\n"
                "          command: npm ci\n"
                "      - save_cache:\n"
                "          paths:\n"
                "            - node_modules\n"
                "          key: v1-dependencies-{{ checksum \"package-lock.json\" }}\n"
            )
        elif self.config.language == Language.GO:
            return (
                "      - restore_cache:\n"
                "          keys:\n"
                "            - go-mod-{{ checksum \"go.mod\" }}\n"
                "      - run:\n"
                "          name: Download dependencies\n"
                "          command: go mod download\n"
                "      - save_cache:\n"
                "          paths:\n"
                "            - /go/pkg/mod\n"
                "          key: go-mod-{{ checksum \"go.mod\" }}\n"
            )
        return ""

    def _build_command(self) -> str:
        """Build command per language."""
        commands = {
            Language.PYTHON: "echo 'No build step for Python'",
            Language.NODEJS: "npm run build",
            Language.GO: "go build -v ./...",
            Language.RUST: "cargo build --release",
            Language.JAVA: "mvn compile",
            Language.DOCKER: "echo 'Docker build in docker_build job'",
        }
        return commands.get(self.config.language, "echo 'Build'")

    def _test_command(self) -> str:
        """Test command per framework."""
        commands = {
            TestFramework.PYTEST: "mkdir -p test-results && pytest -v --junitxml=test-results/junit.xml",
            TestFramework.JEST: "npm test -- --ci --testResultsProcessor=jest-junit",
            TestFramework.MOCHA: "npm run test:mocha",
            TestFramework.GO_TEST: "go test -v ./...",
            TestFramework.CARGO_TEST: "cargo test",
            TestFramework.JUNIT: "mvn test",
        }
        return commands.get(self.config.test_framework, "echo 'No tests'")

    def _lint_command(self) -> str:
        """Lint command per language."""
        commands = {
            Language.PYTHON: "pip install flake8 && flake8 .",
            Language.NODEJS: "npm run lint",
            Language.GO: "go vet ./... && gofmt -d .",
            Language.RUST: "cargo clippy -- -D warnings",
            Language.JAVA: "mvn checkstyle:check",
            Language.DOCKER: "docker run --rm -i hadolint/hadolint < Dockerfile",
        }
        return commands.get(self.config.language, "echo 'No linting'")

    def _security_steps(self) -> str:
        """Security scan steps."""
        steps = ["            docker run --rm -v $(pwd):/project aquasec/trivy fs /project || true"]
        if self.config.language == Language.PYTHON:
            steps.append("            pip install bandit && bandit -r . || true")
        elif self.config.language == Language.NODEJS:
            steps.append("            npm audit || true")
        return "\n".join([f"            {s}" for s in steps]) + "\n"

    def _coverage_command(self) -> str:
        """Coverage command per language."""
        if self.config.language == Language.PYTHON:
            return (
                f"            pip install pytest-cov\n"
                f"            pytest --cov=. --cov-report=xml --cov-report=html --cov-fail-under={self.config.coverage_threshold}"
            )
        elif self.config.language == Language.NODEJS:
            return "            npm run test:coverage"
        elif self.config.language == Language.GO:
            return "            go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out -o coverage_html/"
        return "            echo 'Coverage not configured'"

    def _deploy_command(self) -> str:
        """Deploy command per target."""
        commands = {
            DeployTarget.KUBERNETES: (
                "            echo $KUBECONFIG | base64 -d > ~/.kube/config\n"
                "            kubectl set image deployment/app app=<< pipeline.parameters.docker_image >>:$CIRCLE_SHA1"
            ),
            DeployTarget.HEROKU: (
                "            curl https://cli-assets.heroku.com/install.sh | sh\n"
                "            heroku container:push web --app $HEROKU_APP_NAME\n"
                "            heroku container:release web --app $HEROKU_APP_NAME"
            ),
            DeployTarget.VERCEL: "            npx vercel --token $VERCEL_TOKEN --prod",
            DeployTarget.AWS: (
                "            pip install awscli\n"
                "            aws elasticbeanstalk update-environment --environment-name prod"
            ),
            DeployTarget.DOCKER_HUB: (
                "            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD\n"
                "            docker push << pipeline.parameters.docker_image >>:$CIRCLE_SHA1"
            ),
        }
        return commands.get(self.config.deploy_target, "            echo 'No deployment configured'")
