"""
GitHub Actions pipeline template generator.

Generates GitHub Actions workflow YAML files supporting build, test,
lint, security scan, coverage, and deployment stages.
"""

from dataclasses import dataclass
from typing import Optional

from src.questionnaire import (
    DeployTarget,
    Language,
    NotificationChannel,
    Platform,
    ProjectConfig,
    TestFramework,
)


@dataclass
class StepBlock:
    """Represents a GitHub Actions step block."""
    name: str
    uses: Optional[str] = None
    run: Optional[str] = None
    env: Optional[dict[str, str]] = None
    with_params: Optional[dict[str, str]] = None
    condition: Optional[str] = None

    def render(self, indent: int = 8) -> str:
        """Render step as YAML string."""
        lines = [f"{' ' * indent}- name: {self.name}"]
        if self.uses:
            lines.append(f"{' ' * (indent + 2)}uses: {self.uses}")
        if self.with_params:
            lines.append(f"{' ' * (indent + 2)}with:")
            for key, val in self.with_params.items():
                lines.append(f"{' ' * (indent + 4)}{key}: {val}")
        if self.condition:
            lines.append(f"{' ' * (indent + 2)}if: {self.condition}")
        if self.env:
            lines.append(f"{' ' * (indent + 2)}env:")
            for key, val in self.env.items():
                lines.append(f"{' ' * (indent + 4)}{key}: {val}")
        if self.run:
            lines.append(f"{' ' * (indent + 2)}run: |")
            for line in self.run.split("\n"):
                lines.append(f"{' ' * (indent + 4)}{line.strip()}")
        return "\n".join(lines)


class GitHubActionsTemplate:
    """Template engine for GitHub Actions workflows."""

    def __init__(self, config: ProjectConfig) -> None:
        """Initialize with project configuration."""
        self.config = config
        self.name = config.project_name

    def render(self) -> str:
        """Render the complete GitHub Actions workflow YAML."""
        sections = [
            self._render_header(),
            self._render_triggers(),
            self._render_env(),
            self._render_jobs(),
        ]
        return "\n".join(sections)

    def _render_header(self) -> str:
        """Render workflow name and metadata."""
        return (
            f"# Auto-generated CI/CD Pipeline for {self.name}\n"
            f"# Platform: GitHub Actions\n"
            f"# Generated by cicd-gen\n"
            f"name: CI/CD Pipeline - {self.name}\n"
        )

    def _render_triggers(self) -> str:
        """Render workflow trigger events."""
        branches_yaml = "\n".join(
            [f"      - {b}" for b in self.config.branches_to_track]
        )
        return (
            "on:\n"
            "  push:\n"
            "    branches:\n"
            f"{branches_yaml}\n"
            "  pull_request:\n"
            "    branches:\n"
            f"{branches_yaml}\n"
        )

    def _render_env(self) -> str:
        """Render global environment variables."""
        lines = ["env:"]
        if self.config.docker_enabled:
            lines.append(f"  DOCKER_IMAGE: ghcr.io/${{{{ github.repository }}}}")
        if self.config.deploy_target == DeployTarget.AWS:
            lines.append("  AWS_REGION: us-east-1")
        return "\n".join(lines) + "\n" if len(lines) > 1 else ""

    def _render_jobs(self) -> str:
        """Render all workflow jobs."""
        jobs = [self._render_build_job()]
        if self.config.test_framework.value != "none":
            jobs.append(self._render_test_job())
        if self.config.linting:
            jobs.append(self._render_lint_job())
        if self.config.security_scan:
            jobs.append(self._render_security_job())
        if self.config.code_coverage:
            jobs.append(self._render_coverage_job())
        if self.config.docker_enabled:
            jobs.append(self._render_docker_job())
        if self.config.deploy_target != DeployTarget.NONE:
            jobs.append(self._render_deploy_job())
        if self.config.notification != NotificationChannel.NONE:
            jobs.append(self._render_notify_job())

        return "\n".join(jobs)

    def _render_build_job(self) -> str:
        """Render the build job."""
        setup = self._setup_steps()
        build = self._build_steps()
        steps = setup + build
        steps_yaml = "\n\n".join(steps)

        return (
            "jobs:\n"
            "  build:\n"
            "    name: Build\n"
            "    runs-on: ubuntu-latest\n"
            f"    defaults:\n"
            f"      run:\n"
            f"        working-directory: {self.config.working_directory}\n"
            f"\n{steps_yaml}"
        )

    def _render_test_job(self) -> str:
        """Render the test job."""
        steps = self._setup_steps()
        steps.append(StepBlock(
            name="Run tests",
            run=self._test_command(),
        ).render())
        steps_yaml = "\n\n".join(steps)

        return (
            "\n  test:\n"
            "    name: Test\n"
            "    runs-on: ubuntu-latest\n"
            "    needs: build\n"
            f"    defaults:\n"
            f"      run:\n"
            f"        working-directory: {self.config.working_directory}\n"
            f"\n{steps_yaml}"
        )

    def _render_lint_job(self) -> str:
        """Render the linting/quality job."""
        steps = self._setup_steps()
        steps.append(StepBlock(
            name="Run linter",
            run=self._lint_command(),
        ).render())
        steps_yaml = "\n\n".join(steps)

        return (
            "\n  lint:\n"
            "    name: Lint\n"
            "    runs-on: ubuntu-latest\n"
            f"\n{steps_yaml}"
        )

    def _render_security_job(self) -> str:
        """Render the security scanning job."""
        steps = [
            StepBlock(
                name="Checkout repository",
                uses="actions/checkout@v4",
            ).render(),
            StepBlock(
                name="Run Trivy vulnerability scanner",
                uses="aquasecurity/trivy-action@master",
                with_params={
                    "scan-type": "fs",
                    "format": "sarif",
                    "output": "trivy-results.sarif",
                },
            ).render(),
            StepBlock(
                name="Upload Trivy scan results",
                uses="github/codeql-action/upload-sarif@v2",
                with_params={"sarif_file": "trivy-results.sarif"},
            ).render(),
        ]
        if self.config.language == Language.PYTHON:
            steps.append(StepBlock(
                name="Run Bandit security scan",
                run="pip install bandit && bandit -r . -f json -o bandit-report.json || true",
            ).render())
        elif self.config.language == Language.NODEJS:
            steps.append(StepBlock(
                name="Run npm audit",
                run="npm audit --audit-level=moderate || true",
            ).render())
        steps_yaml = "\n\n".join(steps)

        return (
            "\n  security:\n"
            "    name: Security Scan\n"
            "    runs-on: ubuntu-latest\n"
            "    needs: build\n"
            f"\n{steps_yaml}"
        )

    def _render_coverage_job(self) -> str:
        """Render the code coverage job."""
        steps = self._setup_steps()
        steps.append(StepBlock(
            name="Run tests with coverage",
            run=self._coverage_command(),
        ).render())
        steps.append(StepBlock(
            name="Upload coverage to Codecov",
            uses="codecov/codecov-action@v3",
            with_params={"files": "./coverage.xml", "fail_ci_if_error": "true"},
        ).render())
        steps_yaml = "\n\n".join(steps)

        return (
            "\n  coverage:\n"
            "    name: Code Coverage\n"
            "    runs-on: ubuntu-latest\n"
            "    needs: test\n"
            f"\n{steps_yaml}"
        )

    def _render_docker_job(self) -> str:
        """Render the Docker build/push job."""
        steps = [
            StepBlock(
                name="Checkout repository",
                uses="actions/checkout@v4",
            ).render(),
            StepBlock(
                name="Set up Docker Buildx",
                uses="docker/setup-buildx-action@v3",
            ).render(),
            StepBlock(
                name="Login to Container Registry",
                uses="docker/login-action@v3",
                with_params={
                    "registry": "ghcr.io",
                    "username": "${{ github.actor }}",
                    "password": "${{ secrets.GITHUB_TOKEN }}",
                },
            ).render(),
            StepBlock(
                name="Build and push Docker image",
                uses="docker/build-push-action@v5",
                with_params={
                    "context": ".",
                    "push": "true",
                    "tags": "${{ env.DOCKER_IMAGE }}:${{ github.sha }}",
                    "cache-from": "type=gha",
                    "cache-to": "type=gha,mode=max",
                },
            ).render(),
        ]
        steps_yaml = "\n\n".join(steps)

        return (
            "\n  docker:\n"
            "    name: Docker Build\n"
            "    runs-on: ubuntu-latest\n"
            "    needs: [build, test]\n"
            f"\n{steps_yaml}"
        )

    def _render_deploy_job(self) -> str:
        """Render the deployment job with placeholder for strategy."""
        steps = self._setup_steps()
        steps.append(StepBlock(
            name=f"Deploy to {self.config.deploy_target.value}",
            run=self._deploy_command(),
        ).render())
        steps_yaml = "\n\n".join(steps)

        return (
            "\n  deploy:\n"
            f"    name: Deploy to {self.config.deploy_target.value.upper()}\n"
            "    runs-on: ubuntu-latest\n"
            "    needs: [build, test]\n"
            "    environment: production\n"
            f"\n{steps_yaml}\n"
            "        # <!-- DEPLOY_STRATEGY_PLACEHOLDER -->\n"
        )

    def _render_notify_job(self) -> str:
        """Render the notification job."""
        steps = []
        if self.config.notification in (NotificationChannel.SLACK, NotificationChannel.BOTH):
            steps.append(StepBlock(
                name="Notify Slack",
                uses="slackapi/slack-github-action@v1.24.0",
                with_params={
                    "payload": '{"text":"Pipeline completed for ${{ github.repository }}"}',
                },
                env={"SLACK_WEBHOOK_URL": self.config.slack_webhook or "${{ secrets.SLACK_WEBHOOK }}"},
            ).render())
        if self.config.notification in (NotificationChannel.EMAIL, NotificationChannel.BOTH):
            steps.append(StepBlock(
                name="Send email notification",
                uses="dawidd6/action-send-mail@v3",
                with_params={
                    "server_address": "smtp.gmail.com",
                    "server_port": "587",
                    "username": "${{ secrets.EMAIL_USERNAME }}",
                    "password": "${{ secrets.EMAIL_PASSWORD }}",
                    "subject": "Pipeline notification - ${{ github.repository }}",
                    "to": self.config.email_recipients,
                    "from": "ci-cd-bot@example.com",
                    "body": "Pipeline completed for ${{ github.repository }} on branch ${{ github.ref }}",
                },
            ).render())
        steps_yaml = "\n\n".join(steps)

        return (
            "\n  notify:\n"
            "    name: Notifications\n"
            "    runs-on: ubuntu-latest\n"
            "    needs: [build, test, deploy]\n"
            "    if: always()\n"
            f"\n{steps_yaml}"
        )

    def _setup_steps(self) -> list[str]:
        """Generate checkout and language setup steps."""
        steps = [StepBlock(
            name="Checkout repository",
            uses="actions/checkout@v4",
        ).render()]

        if self.config.language == Language.PYTHON:
            steps.append(StepBlock(
                name="Set up Python",
                uses="actions/setup-python@v5",
                with_params={"python-version": "3.11"},
            ).render())
            steps.append(StepBlock(
                name="Install dependencies",
                run="pip install -r requirements.txt",
            ).render())
        elif self.config.language == Language.NODEJS:
            steps.append(StepBlock(
                name="Set up Node.js",
                uses="actions/setup-node@v4",
                with_params={"node-version": "20", "cache": "npm"},
            ).render())
            steps.append(StepBlock(
                name="Install dependencies",
                run="npm ci",
            ).render())
        elif self.config.language == Language.GO:
            steps.append(StepBlock(
                name="Set up Go",
                uses="actions/setup-go@v5",
                with_params={"go-version": "1.21"},
            ).render())
            steps.append(StepBlock(
                name="Install dependencies",
                run="go mod download",
            ).render())

        return steps

    def _build_steps(self) -> list[str]:
        """Generate language-specific build steps."""
        build_commands: dict[Language, str] = {
            Language.PYTHON: "echo 'No build step required for Python'",
            Language.NODEJS: "npm run build",
            Language.GO: "go build -v ./...",
            Language.RUST: "cargo build --release",
            Language.JAVA: "mvn compile",
            Language.DOCKER: "echo 'Docker build handled in docker job'",
        }
        cmd = build_commands.get(self.config.language, "echo 'Build step'")
        return [StepBlock(name="Build project", run=cmd).render()]

    def _test_command(self) -> str:
        """Generate test command based on test framework."""
        commands: dict[TestFramework, str] = {
            TestFramework.PYTEST: "pytest -v",
            TestFramework.JEST: "npm test",
            TestFramework.MOCHA: "npm run test:mocha",
            TestFramework.GO_TEST: "go test -v ./...",
            TestFramework.CARGO_TEST: "cargo test",
            TestFramework.JUNIT: "mvn test",
        }
        return commands.get(self.config.test_framework, "echo 'No tests configured'")

    def _lint_command(self) -> str:
        """Generate lint command based on language."""
        commands: dict[Language, str] = {
            Language.PYTHON: "pip install flake8 black && flake8 . --max-line-length=88 && black --check .",
            Language.NODEJS: "npm run lint",
            Language.GO: "go vet ./... && gofmt -d .",
            Language.RUST: "cargo clippy -- -D warnings && cargo fmt --check",
            Language.JAVA: "mvn checkstyle:check",
            Language.DOCKER: "docker run --rm -i hadolint/hadolint < Dockerfile",
        }
        return commands.get(self.config.language, "echo 'No linting configured'")

    def _coverage_command(self) -> str:
        """Generate coverage command with threshold."""
        threshold = self.config.coverage_threshold
        if self.config.language == Language.PYTHON:
            return (
                f"pip install pytest-cov && "
                f"pytest --cov=. --cov-report=xml --cov-report=html "
                f"--cov-fail-under={threshold}"
            )
        elif self.config.language == Language.NODEJS:
            return f"npm run test:coverage -- --coverage --collectCoverageFrom='src/**/*.js'"
        elif self.config.language == Language.GO:
            return f"go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out -o coverage.html"
        return "echo 'Coverage not configured'"

    def _deploy_command(self) -> str:
        """Generate deployment command based on target."""
        commands: dict[DeployTarget, str] = {
            DeployTarget.AWS: (
                "aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && "
                "aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && "
                "aws elasticbeanstalk update-environment --environment-name prod"
            ),
            DeployTarget.KUBERNETES: (
                "echo ${{ secrets.KUBECONFIG }} | base64 -d > kubeconfig && "
                "export KUBECONFIG=kubeconfig && "
                "kubectl set image deployment/app app=${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
            ),
            DeployTarget.HEROKU: (
                "curl https://cli-assets.heroku.com/install.sh | sh && "
                "heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }} && "
                "heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}"
            ),
            DeployTarget.VERCEL: "npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod",
            DeployTarget.DOCKER_HUB: (
                "docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} && "
                "docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
            ),
        }
        return commands.get(
            self.config.deploy_target,
            "echo 'No deployment target configured'"
        )
