"""
GitLab CI pipeline template generator.

Generates .gitlab-ci.yml configurations with stages for build, test,
security scanning, coverage reporting, and deployment.
"""

from src.questionnaire import (
    DeployTarget,
    Language,
    NotificationChannel,
    ProjectConfig,
    TestFramework,
)


class GitLabCITemplate:
    """Template engine for GitLab CI pipelines."""

    def __init__(self, config: ProjectConfig) -> None:
        """Initialize with project configuration."""
        self.config = config

    def render(self) -> str:
        """Render the complete .gitlab-ci.yml content."""
        sections = [
            self._render_header(),
            self._render_variables(),
            self._render_stages(),
            self._render_cache(),
            self._render_build_job(),
        ]
        if self.config.test_framework.value != "none":
            sections.append(self._render_test_job())
        if self.config.linting:
            sections.append(self._render_lint_job())
        if self.config.security_scan:
            sections.append(self._render_security_job())
        if self.config.code_coverage:
            sections.append(self._render_coverage_job())
        if self.config.docker_enabled:
            sections.append(self._render_docker_job())
        if self.config.deploy_target != DeployTarget.NONE:
            sections.append(self._render_deploy_job())
        if self.config.notification != NotificationChannel.NONE:
            sections.append(self._render_notify_job())

        return "\n".join(sections)

    def _render_header(self) -> str:
        """Render header comments."""
        return (
            f"# Auto-generated CI/CD Pipeline for {self.config.project_name}\n"
            "# Platform: GitLab CI\n"
            "# Generated by cicd-gen\n"
        )

    def _render_variables(self) -> str:
        """Render global variables."""
        lines = ["variables:"]
        if self.config.docker_enabled:
            lines.append(f"  DOCKER_IMAGE: \"$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA\"")
            lines.append("  DOCKER_DRIVER: overlay2")
            lines.append("  DOCKER_TLS_CERTDIR: \"\"")
        return "\n".join(lines) + "\n\n"

    def _render_stages(self) -> str:
        """Render pipeline stages."""
        stages = ["build"]
        if self.config.test_framework.value != "none":
            stages.append("test")
        if self.config.linting:
            stages.append("lint")
        if self.config.security_scan:
            stages.append("security")
        if self.config.code_coverage:
            stages.append("coverage")
        if self.config.docker_enabled:
            stages.append("docker")
        if self.config.deploy_target != DeployTarget.NONE:
            stages.append("deploy")
        if self.config.notification != NotificationChannel.NONE:
            stages.append("notify")

        stages_yaml = "\n".join([f"  - {s}" for s in stages])
        return f"stages:\n{stages_yaml}\n\n"

    def _render_cache(self) -> str:
        """Render cache configuration."""
        if self.config.language == Language.PYTHON:
            return (
                ".python_cache:\n"
                "  cache:\n"
                "    key: ${CI_COMMIT_REF_SLUG}\n"
                "    paths:\n"
                "      - .cache/pip\n"
                "\n"
            )
        elif self.config.language == Language.NODEJS:
            return (
                ".node_cache:\n"
                "  cache:\n"
                "    key: ${CI_COMMIT_REF_SLUG}\n"
                "    paths:\n"
                "      - node_modules/\n"
                "\n"
            )
        elif self.config.language == Language.GO:
            return (
                ".go_cache:\n"
                "  cache:\n"
                "    key: ${CI_COMMIT_REF_SLUG}\n"
                "    paths:\n"
                "      - /go/pkg/mod\n"
                "\n"
            )
        return ""

    def _render_build_job(self) -> str:
        """Render build job."""
        image = self._docker_image()
        script = self._build_script()
        cache = self._cache_ref()

        job = (
            "build:\n"
            "  stage: build\n"
            f"  image: {image}\n"
        )
        if cache:
            job += f"  {cache}\n"
        job += (
            "  script:\n"
            f"    - {script}\n"
            "  artifacts:\n"
            "    paths:\n"
            "      - build/\n"
            "    expire_in: 1 hour\n"
            "  rules:\n"
            "    - if: $CI_COMMIT_BRANCH\n"
        )
        return job + "\n"

    def _render_test_job(self) -> str:
        """Render test job."""
        image = self._docker_image()
        script = self._test_script()
        cache = self._cache_ref()

        job = (
            "test:\n"
            "  stage: test\n"
            "  needs: [build]\n"
            f"  image: {image}\n"
        )
        if cache:
            job += f"  {cache}\n"
        job += (
            "  script:\n"
            f"    - {script}\n"
            "  artifacts:\n"
            "    reports:\n"
            "      junit: test-results.xml\n"
            "    when: always\n"
        )
        return job + "\n"

    def _render_lint_job(self) -> str:
        """Render lint job."""
        image = self._docker_image()
        script = self._lint_script()

        return (
            "lint:\n"
            "  stage: lint\n"
            f"  image: {image}\n"
            "  script:\n"
            f"    - {script}\n"
            "  rules:\n"
            "    - if: $CI_COMMIT_BRANCH\n"
            "\n"
        )

    def _render_security_job(self) -> str:
        """Render security scan job."""
        image = self._docker_image()
        scripts = ["echo 'Running security scan'"]
        if self.config.language == Language.PYTHON:
            scripts.append("pip install bandit && bandit -r . -f json -o bandit-report.json || true")
        elif self.config.language == Language.NODEJS:
            scripts.append("npm audit --audit-level=moderate || true")

        scripts.append("docker run --rm -v $(pwd):/project aquasec/trivy fs --format json -o trivy-report.json /project || true")

        script_lines = "\n".join([f"    - {s}" for s in scripts])
        return (
            "security:\n"
            "  stage: security\n"
            "  needs: [build]\n"
            f"  image: {image}\n"
            "  script:\n"
            f"{script_lines}\n"
            "  artifacts:\n"
            "    paths:\n"
            "      - bandit-report.json\n"
            "      - trivy-report.json\n"
            "  rules:\n"
            "    - if: $CI_COMMIT_BRANCH\n"
            "\n"
        )

    def _render_coverage_job(self) -> str:
        """Render coverage job."""
        image = self._docker_image()
        script = self._coverage_script()
        threshold = self.config.coverage_threshold

        return (
            "coverage:\n"
            "  stage: coverage\n"
            "  needs: [test]\n"
            f"  image: {image}\n"
            "  script:\n"
            f"    - {script}\n"
            "  coverage: '/TOTAL\\s+\\d+\\s+\\d+\\s+(\\d+%)/'\n"
            "  artifacts:\n"
            "    reports:\n"
            "      coverage_report:\n"
            "        coverage_format: cobertura\n"
            "        path: coverage.xml\n"
            "  rules:\n"
            f"    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH == \"{self.config.branches_to_track[0]}\"\n"
            "\n"
        )

    def _render_docker_job(self) -> str:
        """Render Docker build job."""
        return (
            "docker_build:\n"
            "  stage: docker\n"
            "  needs: [build, test]\n"
            "  image: docker:latest\n"
            "  services:\n"
            "    - docker:dind\n"
            "  before_script:\n"
            "    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY\n"
            "  script:\n"
            f"    - docker build -t $DOCKER_IMAGE -f {self.config.dockerfile_path} .\n"
            "    - docker push $DOCKER_IMAGE\n"
            "  rules:\n"
            f"    - if: $CI_COMMIT_BRANCH == \"{self.config.branches_to_track[0]}\"\n"
            "\n"
        )

    def _render_deploy_job(self) -> str:
        """Render deployment job."""
        deploy_script = self._deploy_script()

        job = (
            "deploy:\n"
            "  stage: deploy\n"
            "  needs: [build, test]\n"
            "  script:\n"
            f"    - {deploy_script}\n"
            "  environment:\n"
            "    name: production\n"
            "    url: https://example.com\n"
            "  rules:\n"
            f"    - if: $CI_COMMIT_BRANCH == \"{self.config.branches_to_track[0]}\" && $CI_PIPELINE_SOURCE != \"schedule\"\n"
            "\n"
            "        # <!-- DEPLOY_STRATEGY_PLACEHOLDER -->\n\n"
        )
        return job

    def _render_notify_job(self) -> str:
        """Render notification job."""
        scripts = []
        if self.config.notification in (NotificationChannel.SLACK, NotificationChannel.BOTH):
            scripts.append(
                f"curl -X POST -H 'Content-type: application/json' "
                f"--data '{{{{\"text\":\"Pipeline {{$CI_PIPELINE_STATUS}} for {{$CI_PROJECT_NAME}}\"}}}}' "
                f"{self.config.slack_webhook or '$SLACK_WEBHOOK_URL'}"
            )

        script_lines = "\n".join([f"    - {s}" for s in scripts])
        return (
            "notify:\n"
            "  stage: notify\n"
            "  needs: [deploy]\n"
            "  script:\n"
            f"{script_lines}\n"
            "  rules:\n"
            "    - if: $CI_COMMIT_BRANCH\n"
            "  when: always\n"
            "\n"
        )

    def _docker_image(self) -> str:
        """Select Docker image based on language."""
        images = {
            Language.PYTHON: "python:3.11-slim",
            Language.NODEJS: "node:20-slim",
            Language.GO: "golang:1.21",
            Language.RUST: "rust:1.75",
            Language.JAVA: "maven:3.9-eclipse-temurin-21",
            Language.DOCKER: "docker:latest",
        }
        return images.get(self.config.language, "ubuntu:latest")

    def _cache_ref(self) -> str:
        """Get cache reference based on language."""
        caches = {
            Language.PYTHON: "extends: .python_cache",
            Language.NODEJS: "extends: .node_cache",
            Language.GO: "extends: .go_cache",
        }
        return caches.get(self.config.language, "")

    def _build_script(self) -> str:
        """Build script per language."""
        scripts = {
            Language.PYTHON: "pip install -r requirements.txt",
            Language.NODEJS: "npm ci && npm run build",
            Language.GO: "go mod download && go build -v ./...",
            Language.RUST: "cargo build --release",
            Language.JAVA: "mvn compile",
            Language.DOCKER: "echo 'Docker build in docker stage'",
        }
        return scripts.get(self.config.language, "echo 'Build step'")

    def _test_script(self) -> str:
        """Test script per framework."""
        scripts = {
            TestFramework.PYTEST: "pytest -v --junitxml=test-results.xml",
            TestFramework.JEST: "npm test -- --ci --reporters=default --reporters=jest-junit",
            TestFramework.MOCHA: "npm run test:mocha",
            TestFramework.GO_TEST: "go test -v ./...",
            TestFramework.CARGO_TEST: "cargo test",
            TestFramework.JUNIT: "mvn test",
        }
        return scripts.get(self.config.test_framework, "echo 'No tests configured'")

    def _lint_script(self) -> str:
        """Lint script per language."""
        scripts = {
            Language.PYTHON: "pip install flake8 black && flake8 . && black --check .",
            Language.NODEJS: "npm run lint",
            Language.GO: "go vet ./... && gofmt -d .",
            Language.RUST: "cargo clippy -- -D warnings && cargo fmt --check",
            Language.JAVA: "mvn checkstyle:check",
            Language.DOCKER: "docker run --rm -i hadolint/hadolint < Dockerfile",
        }
        return scripts.get(self.config.language, "echo 'No linting'")

    def _coverage_script(self) -> str:
        """Coverage script with threshold."""
        if self.config.language == Language.PYTHON:
            return (
                f"pip install pytest-cov && "
                f"pytest --cov=. --cov-report=xml --cov-report=html "
                f"--cov-fail-under={self.config.coverage_threshold}"
            )
        elif self.config.language == Language.NODEJS:
            return "npm run test:coverage"
        elif self.config.language == Language.GO:
            return "go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out -o coverage.html"
        return "echo 'Coverage not configured'"

    def _deploy_script(self) -> str:
        """Deployment script per target."""
        scripts = {
            DeployTarget.KUBERNETES: (
                "kubectl config use-context production && "
                "kubectl set image deployment/app app=$DOCKER_IMAGE"
            ),
            DeployTarget.AWS: (
                "pip install awscli && "
                "aws elasticbeanstalk update-environment --environment-name prod"
            ),
            DeployTarget.HEROKU: (
                "curl https://cli-assets.heroku.com/install.sh | sh && "
                "heroku container:push web --app $HEROKU_APP_NAME"
            ),
            DeployTarget.DOCKER_HUB: (
                "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && "
                "docker push $DOCKER_IMAGE"
            ),
        }
        return scripts.get(
            self.config.deploy_target,
            "echo 'No deployment configured'"
        )
