"""
Jenkins pipeline template generator (declarative syntax).

Generates Jenkinsfile configurations with parallel stages,
quality gates, and post-build actions.
"""

from src.questionnaire import (
    DeployTarget,
    Language,
    NotificationChannel,
    ProjectConfig,
    TestFramework,
)


class JenkinsTemplate:
    """Template engine for Jenkins declarative pipelines."""

    def __init__(self, config: ProjectConfig) -> None:
        """Initialize with project configuration."""
        self.config = config

    def render(self) -> str:
        """Render the complete Jenkinsfile content."""
        sections = [
            self._render_header(),
            self._render_pipeline_open(),
            self._render_agent(),
            self._render_environment(),
            self._render_options(),
            self._render_triggers(),
            self._render_stages(),
            self._render_post(),
            self._render_pipeline_close(),
        ]
        return "\n".join(sections)

    def _render_header(self) -> str:
        """Render header comments."""
        return (
            f"/* Auto-generated CI/CD Pipeline for {self.config.project_name} */\n"
            "/* Platform: Jenkins (Declarative Pipeline) */\n"
            "/* Generated by cicd-gen */\n"
        )

    def _render_pipeline_open(self) -> str:
        """Render pipeline block start."""
        return "pipeline {"

    def _render_agent(self) -> str:
        """Render agent configuration."""
        agent_images = {
            Language.PYTHON: "python:3.11-slim",
            Language.NODEJS: "node:20-slim",
            Language.GO: "golang:1.21",
            Language.RUST: "rust:1.75",
            Language.JAVA: "maven:3.9-eclipse-temurin-21",
        }
        image = agent_images.get(self.config.language, "any")
        return (
            f'\n    agent {{ docker {{ image \'{image}\' }} }}'
        )

    def _render_environment(self) -> str:
        """Render environment block."""
        lines = ["\n    environment {"]
        if self.config.docker_enabled:
            lines.append('        DOCKER_IMAGE = "registry.io/${env.JOB_NAME}:${env.BUILD_NUMBER}"')
        if self.config.code_coverage:
            lines.append(f"        COVERAGE_THRESHOLD = '{self.config.coverage_threshold}'")
        if self.config.notification in (NotificationChannel.SLACK, NotificationChannel.BOTH):
            lines.append('        SLACK_WEBHOOK = credentials("slack-webhook")')
        if self.config.notification in (NotificationChannel.EMAIL, NotificationChannel.BOTH):
            lines.append(f'        EMAIL_RECIPIENTS = "{self.config.email_recipients}"')
        lines.append("    }")
        return "\n".join(lines)

    def _render_options(self) -> str:
        """Render pipeline options."""
        return """
    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        timestamps()
    }"""

    def _render_triggers(self) -> str:
        """Render SCM triggers."""
        return """
    triggers {
        pollSCM('H/5 * * * *')
    }"""

    def _render_stages(self) -> str:
        """Render all pipeline stages."""
        stages = [
            self._render_build_stage(),
        ]
        if self.config.test_framework.value != "none":
            stages.append(self._render_test_stage())
        if self.config.linting:
            stages.append(self._render_lint_stage())
        if self.config.security_scan:
            stages.append(self._render_security_stage())
        if self.config.code_coverage:
            stages.append(self._render_coverage_stage())
        if self.config.docker_enabled:
            stages.append(self._render_docker_stage())
        if self.config.deploy_target != DeployTarget.NONE:
            stages.append(self._render_deploy_stage())

        stages_content = "\n".join(stages)
        return f"\n    stages {{\n{stages_content}\n    }}"

    def _render_build_stage(self) -> str:
        """Render build stage."""
        script = self._build_script()
        return (
            "\n        stage('Build') {\n"
            "            steps {\n"
            "                script {\n"
            f"                    {script}\n"
            "                }\n"
            "            }\n"
            "        }"
        )

    def _render_test_stage(self) -> str:
        """Render test stage with parallel execution."""
        script = self._test_script()
        return (
            "\n        stage('Test') {\n"
            "            steps {\n"
            "                script {\n"
            f"                    {script}\n"
            "                }\n"
            "            }\n"
            "            post {\n"
            "                always {\n"
            "                    junit '**/test-results.xml'\n"
            "                }\n"
            "            }\n"
            "        }"
        )

    def _render_lint_stage(self) -> str:
        """Render lint stage."""
        script = self._lint_script()
        return (
            "\n        stage('Lint') {\n"
            "            steps {\n"
            "                script {\n"
            f"                    {script}\n"
            "                }\n"
            "            }\n"
            "        }"
        )

    def _render_security_stage(self) -> str:
        """Render security scan stage."""
        return (
            "\n        stage('Security Scan') {\n"
            "            parallel {\n"
            "                stage('Trivy Scan') {\n"
            "                    steps {\n"
            "                        sh '''\n"
            "                            docker run --rm -v $(pwd):/project \\\n"
            "                            aquasec/trivy fs --exit-code 0 \\\n"
            "                            --format json -o trivy-report.json /project\n"
            "                        '''\n"
            "                    }\n"
            "                }\n"
            "                stage('SAST') {\n"
            "                    steps {\n"
            "                        script {\n"
            f"                            {self._sast_script()}\n"
            "                        }\n"
            "                    }\n"
            "                }\n"
            "            }\n"
            "        }"
        )

    def _render_coverage_stage(self) -> str:
        """Render coverage stage with quality gate."""
        script = self._coverage_script()
        threshold = self.config.coverage_threshold
        return (
            "\n        stage('Code Coverage') {\n"
            "            steps {\n"
            "                script {\n"
            f"                    {script}\n"
            "                }\n"
            "            }\n"
            f"            when {{\n"
            f"                expression {{ env.CHANGE_TARGET == '{self.config.branches_to_track[0]}' }}\n"
            "            }\n"
            "            post {\n"
            "                always {\n"
            "                    publishHTML([\n"
            "                        allowMissing: false,\n"
            "                        alwaysLinkToLastBuild: true,\n"
            "                        keepAll: true,\n"
            "                        reportDir: 'coverage_html',\n"
            "                        reportFiles: 'index.html',\n"
            "                        reportName: 'Coverage Report'\n"
            "                    ])\n"
            "                }\n"
            "                failure {\n"
            f"                    error \"Code coverage below {threshold}%\"\n"
            "                }\n"
            "            }\n"
            "        }"
        )

    def _render_docker_stage(self) -> str:
        """Render Docker build/push stage."""
        return (
            "\n        stage('Docker Build') {\n"
            "            steps {\n"
            "                script {\n"
            f"                    docker.build(env.DOCKER_IMAGE, '-f {self.config.dockerfile_path} .')\n"
            "                    docker.withRegistry('https://registry.io', 'registry-credentials') {\n"
            "                        docker.image(env.DOCKER_IMAGE).push()\n"
            "                    }\n"
            "                }\n"
            "            }\n"
            "        }"
        )

    def _render_deploy_stage(self) -> str:
        """Render deployment stage."""
        deploy_steps = self._deploy_script()
        return (
            "\n        stage('Deploy') {\n"
            "            steps {\n"
            "                script {\n"
            "                    input message: 'Approve deployment to production?', ok: 'Deploy'\n"
            f"                    {deploy_steps}\n"
            "                }\n"
            "            }\n"
            "            // <!-- DEPLOY_STRATEGY_PLACEHOLDER -->\n"
            "        }"
        )

    def _render_post(self) -> str:
        """Render post-build actions."""
        blocks = ["\n    post {"]

        blocks.append(
            "        always {\n"
            "            cleanWs()\n"
            "        }"
        )

        if self.config.notification in (NotificationChannel.SLACK, NotificationChannel.BOTH):
            blocks.append(
                "        success {\n"
                "            slackSend(color: 'good', message: \"Build succeeded: ${env.JOB_NAME} #${env.BUILD_NUMBER}\")\n"
                "        }\n"
                "        failure {\n"
                "            slackSend(color: 'danger', message: \"Build failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}\")\n"
                "        }"
            )

        if self.config.notification in (NotificationChannel.EMAIL, NotificationChannel.BOTH):
            blocks.append(
                "        failure {\n"
                "            mail to: env.EMAIL_RECIPIENTS,\n"
                "                 subject: \"Build Failed: ${env.JOB_NAME}\",\n"
                "                 body: \"Build ${env.BUILD_NUMBER} failed. Check console at ${env.BUILD_URL}\"\n"
                "        }"
            )

        blocks.append("    }")
        return "\n".join(blocks)

    def _render_pipeline_close(self) -> str:
        """Close pipeline block."""
        return "\n}"

    def _build_script(self) -> str:
        """Build script for Jenkins."""
        scripts = {
            Language.PYTHON: "sh 'pip install -r requirements.txt'",
            Language.NODEJS: "sh 'npm ci && npm run build'",
            Language.GO: "sh 'go mod download && go build -v ./...'",
            Language.RUST: "sh 'cargo build --release'",
            Language.JAVA: "sh 'mvn compile'",
            Language.DOCKER: "sh 'echo No build step for Docker'",
        }
        return scripts.get(self.config.language, "sh 'echo Build step'")

    def _test_script(self) -> str:
        """Test script for Jenkins."""
        scripts = {
            TestFramework.PYTEST: "sh 'pytest -v --junitxml=test-results.xml'",
            TestFramework.JEST: "sh 'npm test -- --ci'",
            TestFramework.MOCHA: "sh 'npm run test:mocha'",
            TestFramework.GO_TEST: "sh 'go test -v ./...'",
            TestFramework.CARGO_TEST: "sh 'cargo test'",
            TestFramework.JUNIT: "sh 'mvn test'",
        }
        return scripts.get(self.config.test_framework, "sh 'echo No tests'")

    def _lint_script(self) -> str:
        """Lint script for Jenkins."""
        scripts = {
            Language.PYTHON: "sh 'pip install flake8 && flake8 .'",
            Language.NODEJS: "sh 'npm run lint'",
            Language.GO: "sh 'go vet ./... && gofmt -d .'",
            Language.RUST: "sh 'cargo clippy -- -D warnings'",
            Language.JAVA: "sh 'mvn checkstyle:check'",
            Language.DOCKER: "sh 'docker run --rm -i hadolint/hadolint < Dockerfile'",
        }
        return scripts.get(self.config.language, "sh 'echo No linting'")

    def _sast_script(self) -> str:
        """SAST script for Jenkins."""
        if self.config.language == Language.PYTHON:
            return "sh 'pip install bandit && bandit -r . || true'"
        elif self.config.language == Language.NODEJS:
            return "sh 'npm audit || true'"
        return "sh 'echo SAST not configured'"

    def _coverage_script(self) -> str:
        """Coverage script for Jenkins."""
        if self.config.language == Language.PYTHON:
            return (
                f"sh 'pip install pytest-cov && "
                f"pytest --cov=. --cov-report=xml --cov-report=html "
                f"--cov-fail-under={self.config.coverage_threshold}'"
            )
        elif self.config.language == Language.NODEJS:
            return "sh 'npm run test:coverage'"
        elif self.config.language == Language.GO:
            return "sh 'go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out -o coverage_html/index.html'"
        return "sh 'echo Coverage not configured'"

    def _deploy_script(self) -> str:
        """Deploy script for Jenkins."""
        scripts = {
            DeployTarget.KUBERNETES: (
                "sh 'kubectl set image deployment/app "
                "app=${env.DOCKER_IMAGE}'"
            ),
            DeployTarget.AWS: (
                "sh 'aws elasticbeanstalk update-environment "
                "--environment-name prod'"
            ),
            DeployTarget.HEROKU: (
                "sh 'git push https://git.heroku.com/$HEROKU_APP_NAME.git HEAD:main'"
            ),
        }
        return scripts.get(self.config.deploy_target, "sh 'echo No deploy'")
